/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseWheelEvent;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import controller.ProdutoController;
import entidades.Produto;
import static telas.Menu.ta;
import util.Maiusculo;
import util.Util;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author deividnn
 */
public class IProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form IProdutos
     */
    public IProdutos() {
        initComponents();
        txtdescricao.setDocument(new Maiusculo(150));
        txtpreco.setDocument(new Maiusculo(10));
        txtpesquisa.setDocument(new Maiusculo(32));
        txtfornecedor.setDocument(new Maiusculo(100));
        txtcontato.setDocument(new Maiusculo(25));
        txtespec.setDocument(new Maiusculo(2000));
        txtcarac.setDocument(new Maiusculo(2000));

       
        txtdataentrada.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseReleased(MouseEvent e) {
             JXDatePicker picker = new JXDatePicker();
        picker.setDate(Calendar.getInstance().getTime());
        picker.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        
        }
    });

        cancelar();

        DefaultTableModel model = iniciaTabela();

        model.addColumn("CODIGO");
        model.addColumn("DESCRICAO");
        model.addColumn("VALOR DIA");
        model.addColumn("STATUS");
        model.addColumn("ENTRADA");
        model.addColumn("SAIDA");
        model.addColumn("FORNECEDOR");
        model.addColumn("CONTATO");
        model.addColumn("DATA ENTRADA");
        model.addColumn("USUARIO ALTERA");
        model.addColumn("DATA ALTERA");

        atualizaTabela(model);

        tabela.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    bteditar.doClick();
                }
            }
        });
        tabela.addMouseWheelListener((MouseWheelEvent e) -> {
            JTable t = (JTable) e.getSource();
            JViewport vport = sc.getViewport();
            Point vp = vport.getViewPosition();
            vp.translate(0, e.getWheelRotation() * t.getRowHeight() * 3);
            t.scrollRectToVisible(new Rectangle(vp, vport.getSize()));
        });
        tabela.requestFocus();
        selectAndScroll(tabela, 0);
        tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel colModel = tabela.getColumnModel();
        colModel.getColumn(1).setPreferredWidth(400);
        colModel.getColumn(6).setPreferredWidth(200);
        colModel.getColumn(7).setPreferredWidth(200);
        colModel.getColumn(8).setPreferredWidth(150);
        colModel.getColumn(10).setPreferredWidth(150);
        
        txtdataentrada.setFormats(new SimpleDateFormat("dd/MM/yyyy"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtdescricao = new javax.swing.JTextField();
        ldata = new javax.swing.JLabel();
        lusuario = new javax.swing.JLabel();
        cstatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtpreco = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfornecedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcontato = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtentrada = new javax.swing.JFormattedTextField();
        txtsaida = new javax.swing.JFormattedTextField();
        txtdataentrada = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtespec = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcarac = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        btinserir = new javax.swing.JButton();
        bteditar = new javax.swing.JButton();
        btsalvar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btatualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ccampo = new javax.swing.JComboBox<>();
        txtpesquisa = new javax.swing.JTextField();
        btpesquisar = new javax.swing.JButton();
        sc = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("TELA DE PRODUTOS");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        jLabel1.setText("DESCRIÇÃO");

        jLabel2.setText("STATUS");

        jLabel4.setText("DATA ALTERA");

        jLabel5.setText("VALOR DIA");

        jLabel6.setText("USUARIO ALTERA");

        txtdescricao.setText(".");
        txtdescricao.setName("usuario"); // NOI18N

        ldata.setText(".");

        lusuario.setText(".");

        cstatus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO", "BLOQUEADO" }));

        jLabel8.setText("CODIGO");

        txtcodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtcodigo.setEnabled(false);

        txtpreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtpreco.setName("valor dia"); // NOI18N

        jLabel3.setText("FORNECEDOR");

        txtfornecedor.setName("fornecedor"); // NOI18N

        jLabel7.setText("CONTATO");

        jLabel10.setText("ENTRADA");

        jLabel11.setText("SAIDA");

        jLabel12.setText("DATA ENTRADA");

        txtentrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtentrada.setName("entrada"); // NOI18N

        txtsaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtsaida.setName("saida"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcontato, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(txtsaida)
                            .addComponent(txtdataentrada, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(ldata, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(70, 70, 70)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(57, 57, 57)
                            .addComponent(jLabel3)
                            .addGap(264, 264, 264)
                            .addComponent(jLabel7)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(212, 212, 212)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addGap(3, 3, 3)
                .addComponent(txtdataentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel1))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7))
                    .addGap(37, 37, 37)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(3, 3, 3)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ldata, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("DADOS DO PRODUTO", jPanel1);

        jLabel13.setText("ESPECIFICAÇÕES:");

        txtespec.setColumns(20);
        txtespec.setRows(5);
        jScrollPane1.setViewportView(txtespec);

        txtcarac.setColumns(20);
        txtcarac.setRows(5);
        jScrollPane2.setViewportView(txtcarac);

        jLabel14.setText("CARACTERISTICAS:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ESPECIFICACOES X CARACTERISTICAS", jPanel2);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        btinserir.setText("INSERIR");
        btinserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinserirActionPerformed(evt);
            }
        });

        bteditar.setText("EDITAR");
        bteditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditarActionPerformed(evt);
            }
        });

        btsalvar.setText("SALVAR");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btcancelar.setText("CANCELAR");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        btatualizar.setText("ATUALIZAR");
        btatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btatualizarActionPerformed(evt);
            }
        });

        jLabel9.setText("PESQUISAR POR:");

        ccampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CODIGO", "DESCRICAO", "STATU", "VALOR_DIA", "ENTRADA", "SAIDA", "FORNECEDOR", "CONTATO" }));
        ccampo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ccampoItemStateChanged(evt);
            }
        });

        txtpesquisa.setText(".");

        btpesquisar.setText("PESQUISAR");
        btpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesquisarActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        sc.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sc)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btinserir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bteditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btcancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btatualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ccampo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btinserir)
                        .addComponent(bteditar)
                        .addComponent(btsalvar)
                        .addComponent(btcancelar)
                        .addComponent(btatualizar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ccampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btpesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sc, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btinserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinserirActionPerformed
        // TODO add your handling code here:
        inserirEditar();
        txtdescricao.setText("");
        txtpreco.setText("");
        lusuario.setText("");
        txtcodigo.setText("");
        txtfornecedor.setText("");
        txtcontato.setText("");
        txtespec.setText("");
        txtcarac.setText("");
        txtentrada.setText("");
        txtsaida.setText("");
        ldata.setText("");
        cstatus.setSelectedItem("ATIVO");
        txtdescricao.requestFocus();
        mostrarForm();
        emedicao = true;
    }//GEN-LAST:event_btinserirActionPerformed

    private void bteditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditarActionPerformed
        // TODO add your handling code here:
        inserirEditar();

        txtcodigo.setText("" + tabela.getValueAt(tabela.getSelectedRow(), 0));
        txtdescricao.setText((String) tabela.getValueAt(tabela.getSelectedRow(), 1));

        Object objp = tabela.getValueAt(tabela.getSelectedRow(), 2);
        if (objp instanceof String) {
            txtpreco.setText(objp.toString());
        }
        cstatus.setSelectedItem((String) tabela.getValueAt(tabela.getSelectedRow(), 3));
        txtentrada.setText(String.valueOf(tabela.getValueAt(tabela.getSelectedRow(), 4)));
        txtsaida.setText(String.valueOf( tabela.getValueAt(tabela.getSelectedRow(), 5)));
        txtfornecedor.setText((String) tabela.getValueAt(tabela.getSelectedRow(), 6));
        txtcontato.setText((String) tabela.getValueAt(tabela.getSelectedRow(), 7));
        
        Object objx = tabela.getValueAt(tabela.getSelectedRow(), 8);
        if (objx instanceof String) {
            try {
                txtdataentrada.getEditor().setValue(Util.datalegivel.parse((String) objx));
            } catch (ParseException ex) {
                Logger.getLogger(IProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        lusuario.setText("" + tabela.getValueAt(tabela.getSelectedRow(), 9));

        Object obj = tabela.getValueAt(tabela.getSelectedRow(), 10);
        if (obj instanceof String) {
            ldata.setText(obj.toString());
        }

        txtdescricao.requestFocus();
        mostrarForm();
        emedicao = true;
    }//GEN-LAST:event_bteditarActionPerformed

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        // TODO add your handling code here:
        try {

            boolean ok = true;

            List<JTextField> txt = new ArrayList<>();
            txt.add(txtdescricao);
            txt.add(txtpreco);
            txt.add(txtfornecedor);
            txt.add(txtentrada);
            txt.add(txtsaida);
       
            if (txtcodigo.getText() == null) {
                txtcodigo.setText("");
            }

            ok = Util.camposVazio(ok, txt);

            if (ok) {
                if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja salvar?", "WARNING",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    Produto u = new Produto();
                    u.setDescricao(txtdescricao.getText());
                    u.setStatus(cstatus.getSelectedItem().toString());
                    u.setUsuarioAltera(Menu.idusuario);
                    u.setFornecedor(txtfornecedor.getText());
                    u.setContato(txtcontato.getText());
                    u.setEntrada(Integer.valueOf(txtentrada.getText()));
                    u.setSaida(Integer.valueOf(txtsaida.getText()));
                    u.setCaracteristicas(txtcarac.getText());
                    u.setEspecificacoes(txtespec.getText());
                    u.setDataentrada((Date)txtdataentrada.getEditor().getValue());
                    u.setValordia(new BigDecimal(txtpreco.getText().replaceAll("\\.", "").replaceAll(",", ".")));
                    if (!txtcodigo.getText().isEmpty()) {
                        u.setId(new Long(txtcodigo.getText()));
                    }

                    if (u.getId() == null) {
                        if (new ProdutoController().salvar(u)) {
                            JOptionPane.showMessageDialog(null, "produto salvo com sucesso");
                            esconderForm();

                            DefaultTableModel model = iniciaTabela();
                            atualizaTabela(model);
                        }
                    } else {
                        if (new ProdutoController().atualizar(u)) {
                            JOptionPane.showMessageDialog(null, "produto salvo com sucesso");
                            esconderForm();

                            DefaultTableModel model = iniciaTabela();
                            atualizaTabela(model);
                        }
                    }
                } else {
                    // no option
                }
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        // TODO add your handling code here:
        try {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar?", "WARNING",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                cancelar();
            } else {
                // no option
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btatualizarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = iniciaTabela();
        atualizaTabela(model);
    }//GEN-LAST:event_btatualizarActionPerformed

    private void ccampoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ccampoItemStateChanged
        // TODO add your handling code here:
        txtpesquisa.requestFocus();
    }//GEN-LAST:event_ccampoItemStateChanged

    private void btpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesquisarActionPerformed
        // TODO add your handling code here:
        txtpesquisa.requestFocus();
        boolean ok = true;
        if (txtpesquisa.getText() == null) {
            txtpesquisa.setText("");
        }

        if (ok) {
            DefaultTableModel model = iniciaTabela();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();

            String campo = "id";
            if (!ccampo.getSelectedItem().toString().equals("CODIGO")) {
                campo = ccampo.getSelectedItem().toString().toLowerCase();
            }

            List<Produto> lista = new ProdutoController().pesquisar(txtpesquisa.getText(), campo);
            lista.forEach((u) -> {
                model.addRow(new Object[]{u.getId(),
                    u.getDescricao(),
                    Util.numero.format(u.getValordia()),
                    u.getStatus(),
                    u.getEntrada(),
                    u.getSaida(),
                    u.getFornecedor(),
                    u.getContato(),
                    Util.datahoralegivel.format(u.getDataentrada()),
                    u.getUsuarioAltera(),
                    Util.datahoralegivel.format(u.getDataAltera())
                });
            });
            model.fireTableDataChanged();
            tabela.setDefaultEditor(Object.class, null);

        }
    }//GEN-LAST:event_btpesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        Long id = (Long) tabela.getValueAt(tabela.getSelectedRow(), 0);
        if (id != null) {
            bteditar.setVisible(true);
            bteditar.setEnabled(true);
        } else {
            bteditar.setVisible(true);
            bteditar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        if (emedicao) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair dessa tela?", "WARNING",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                removertela();
                dispose();
            }
        } else {
            removertela();
            dispose();
        }
    }//GEN-LAST:event_formInternalFrameClosing

    public void removertela() {
        Menu.telas.remove(Menu.telas.getSelectedIndex());
        for (Component c : ta.getMenuComponents()) {
            if (c instanceof JMenuItem) {
                if (c.getName().equals(getTitle().trim())) {
                    ta.remove(c);
                    break;
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btatualizar;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton bteditar;
    private javax.swing.JButton btinserir;
    private javax.swing.JButton btpesquisar;
    private javax.swing.JButton btsalvar;
    private javax.swing.JComboBox<String> ccampo;
    private javax.swing.JComboBox<String> cstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel ldata;
    private javax.swing.JLabel lusuario;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane sc;
    private javax.swing.JTable tabela;
    private javax.swing.JTextArea txtcarac;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcontato;
    private org.jdesktop.swingx.JXDatePicker txtdataentrada;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JFormattedTextField txtentrada;
    private javax.swing.JTextArea txtespec;
    private javax.swing.JTextField txtfornecedor;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JFormattedTextField txtpreco;
    private javax.swing.JFormattedTextField txtsaida;
    // End of variables declaration//GEN-END:variables

    public static boolean emedicao;

    private void atualizaTabela(DefaultTableModel model) {

        /**
         *
         * model.addColumn("CODIGO"); model.addColumn("DESCRICAO");
         * model.addColumn("VALOR DIA"); model.addColumn("STATUS");
         * model.addColumn("ENTRADA"); model.addColumn("SAIDA");
         * model.addColumn("FORNECEDOR"); model.addColumn("CONTATO");
         * model.addColumn("DATA ENTRADA"); model.addColumn("USUARIO ALTERA");
         * model.addColumn("DATA ALTERA");
         */
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        List<Produto> lista = new ProdutoController().lista();
        lista.forEach((u) -> {
            model.addRow(new Object[]{u.getId(),
                u.getDescricao(),
                Util.numero.format(u.getValordia()),
                u.getStatus(),
                u.getEntrada(),
                u.getSaida(),
                u.getFornecedor(),
                u.getContato(),
                Util.datalegivel.format(u.getDataentrada()),
                u.getUsuarioAltera(),
                Util.datahoralegivel.format(u.getDataAltera())
            });
        });
        model.fireTableDataChanged();
        tabela.setDefaultEditor(Object.class, null);

    }

    private void inserirEditar() {
        btinserir.setEnabled(false);
        bteditar.setEnabled(false);
        btsalvar.setEnabled(true);
        btcancelar.setEnabled(true);
        btatualizar.setEnabled(false);
        btpesquisar.setEnabled(false);
    }

    private void cancelar() {
        emedicao = false;
        btinserir.setEnabled(true);
        esconderForm();
        btatualizar.setEnabled(true);
        btpesquisar.setEnabled(true);
        txtdescricao.requestFocus();

    }

    private void esconderForm() {
        panel.setVisible(false);
        bteditar.setVisible(false);
        btsalvar.setVisible(false);
        btcancelar.setVisible(false);
        btpesquisar.setEnabled(true);
        ccampo.setEnabled(true);
        txtpesquisa.setEnabled(true);
        btinserir.setEnabled(true);
        btatualizar.setEnabled(true);
        sc.setVisible(true);
    }

    private void mostrarForm() {
        panel.setVisible(true);
        bteditar.setVisible(true);
        btsalvar.setVisible(true);
        btcancelar.setVisible(true);
        btpesquisar.setEnabled(false);
        ccampo.setEnabled(false);
        txtpesquisa.setEnabled(false);
        btinserir.setEnabled(false);
        btatualizar.setEnabled(false);
        sc.setVisible(false);
    }

    private DefaultTableModel iniciaTabela() {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tabela.setRowSorter(sorter);
        return model;
    }

    public static void scrollToVisible(JTable table, int rowIndex) {
        scrollToVisible(table, rowIndex, 0);
    }

    public static void scrollToVisible(JTable table, int rowIndex, int vColIndex) {
        if (!(table.getParent() instanceof JViewport)) {
            return;
        }
    }

    public static Collection<Integer> getReverseSelectedRows(JTable table) {
        Set<Integer> rows = new TreeSet<>((Integer o1, Integer o2) -> o2.compareTo(o1));

        for (int r : table.getSelectedRows()) {
            rows.add(r);
        }

        return rows;
    }

    public static void selectAndScroll(JTable table, int rowIndex) {
        table.getSelectionModel().setSelectionInterval(rowIndex, rowIndex);
        scrollToVisible(table, rowIndex);
    }

}
